<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFrameworks>net9.0</TargetFrameworks>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>

        <EnableWindowsTargeting>true</EnableWindowsTargeting>
        <EnableLinuxTargeting>true</EnableLinuxTargeting>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.13" />
        <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.13" />
        <PackageReference Include="Avalonia.Desktop" Version="11.3.13" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.13" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.13" />
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics" Version="11.3.13">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
        <PackageReference Include="MessageBox.Avalonia" Version="3.3.1.1" />
        <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.5" />
        <PackageReference Include="XmppDotNet" Version="3.2.8" />
        <PackageReference Include="XmppDotNet.Core" Version="3.2.8" />
        <PackageReference Include="XmppDotNet.Extensions" Version="3.2.8" />
        <PackageReference Include="XmppDotNet.Srv" Version="3.2.8" />
        <PackageReference Include="XmppDotNet.Transport.Socket" Version="3.2.8" />
    </ItemGroup>
</Project>
